### ISSUE TITLE
sla oq eu to fazendo

### ISSUE THREAD

**Issue by NiumXp** [NiumXp/github-e-git-na-marra#1]
algo aq mt legal

@NiumXp

**Comment by joaolucasete** [comment]
Sim, realmente é bem incrível seus estudos

**Comment by NiumXp** [comment]
> Sim, realmente é bem incrível seus estudos

Muito obrigado!

**Comment by joaolucasete** [comment]
> > Sim, realmente é bem incrível seus estudos
> 
> Muito obrigado!

por nada meu caro amigo

**Comment by NiumXp** [comment]
#1

**Comment by NiumXp** [comment]
#4
